services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=bullet
      - POSTGRES_PASSWORD=bullet
      - POSTGRES_DB=bullet
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    image: bullet
    env_file:
      - .env
    environment:
      - DEBUG=True
      - PARENT_HOST=localhost:8000
      - REDIS_RQ_ASYNC=False
      - LETTER_URL=http://letter:8080
      - LETTER_CALLBACK_ROOT=http://math.localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - geiop_data:/geoip/
      - ./uploads:/app/uploads
    develop:
      watch:
        - action: sync
          path: ./bullet
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./pyproject.toml

    depends_on:
      - db
      - geoip
      - meilisearch
    command: "/app/start.sh dev"

  tailwind:
    build:
      context: .
      target: cssbuild
    volumes:
      - ./bullet/:/app/bullet/
      - ./css:/app/css/
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    tty: true

  geoip:
    image: maxmindinc/geoipupdate
    env_file:
      - .env
    volumes:
      - geiop_data:/usr/share/GeoIP

  meilisearch:
    image: getmeili/meilisearch:v1.12.5
    volumes:
      - search_data:/meili_data

  redis:
    image: redis:7.2.0

  letter:
    image: ghcr.io/naboj-org/letter:latest
    extra_hosts:
      - math.localhost:host-gateway

volumes:
  postgres_data:
  geiop_data:
  search_data:
